# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonateAim',
            fields=[
                ('year', models.PositiveIntegerField(help_text='Jahr (4-stellig)', primary_key=True, serialize=False, verbose_name='Jahr')),
                ('aim', models.PositiveIntegerField(help_text='Spendenziel in Cent', verbose_name='Spendenziel')),
                ('current', models.PositiveIntegerField(help_text='Aktueller Stand in Cent', verbose_name='Aktuell')),
            ],
        ),
    ]
