# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_o_meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateaim',
            name='current',
            field=models.PositiveIntegerField(default=0, help_text='Aktueller Stand in Cent', verbose_name='Aktuell'),
        ),
    ]
