# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(help_text='Name der Organisation', max_length=100, verbose_name='Organisation')),
                ('person_responsible', models.CharField(help_text='Name der Person, die verantwortlich ist', max_length=100, verbose_name='Verantwortliche*r')),
                ('street', models.CharField(help_text='Straße', max_length=100, verbose_name='Straße')),
                ('zip_code', models.CharField(help_text='Postleitzahl', max_length=5, verbose_name='PLZ')),
                ('city', models.CharField(help_text='Ort', max_length=100, verbose_name='Ort')),
                ('phone', models.CharField(help_text='Telefonnummer', max_length=20, verbose_name='Telefon')),
                ('mail', models.EmailField(help_text='E-Mail für weiteren Kontakt', max_length=254, verbose_name='E-Mail')),
            ],
        ),
        migrations.CreateModel(
            name='InfoBoothRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Thema des Standes', max_length=500, verbose_name='Thema')),
                ('size', models.CharField(help_text='Größe des Standes, L x B in cm', max_length=100, verbose_name='Größe')),
                ('notes', models.TextField(help_text='Sonstige Anmerkungen', max_length=500, verbose_name='Sonstiges')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Größe des Wagens, L x B x H in cm', max_length=100, verbose_name='Größe')),
                ('equipment', models.CharField(help_text='Technische Ausstattung, z.B. Anlagen, Generatoren', max_length=500, verbose_name='Technische Ausstattung')),
                ('show', models.TextField(help_text='Artists, Musikgenre, Performances; kurz  zusammengefasst', max_length=500, verbose_name='Programm')),
                ('decoration', models.TextField(help_text='Falls ihr schon Ideen zur Dekoration habt', max_length=500, verbose_name='Deko')),
                ('notes', models.TextField(help_text='Sonstige Anmerkungen', max_length=500, verbose_name='Sonstiges')),
            ],
        ),
        migrations.CreateModel(
            name='WalkingGroupRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveIntegerField(help_text='Ungefähre Anzahl der Teilnehmer*innen', verbose_name='Teilnehmer*innen Anzahl')),
                ('show', models.TextField(help_text='Artists, Musikgenre, Performances; kurz  zusammengefasst', max_length=500, verbose_name='Programm')),
                ('music', models.BooleanField(help_text='Wird Musik gespielt?', verbose_name='Musik')),
                ('notes', models.TextField(help_text='Sonstige Anmerkungen', max_length=500, verbose_name='Sonstiges')),
            ],
        ),
    ]
