# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoboothregistration',
            name='notes',
            field=models.TextField(blank=True, help_text='Sonstige Anmerkungen', max_length=500, verbose_name='Sonstiges'),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='decoration',
            field=models.TextField(blank=True, help_text='Falls ihr schon Ideen zur Dekoration habt', max_length=500, verbose_name='Deko'),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='equipment',
            field=models.CharField(blank=True, help_text='Technische Ausstattung, z.B. Anlagen, Generatoren', max_length=500, verbose_name='Technische Ausstattung'),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='notes',
            field=models.TextField(blank=True, help_text='Sonstige Anmerkungen', max_length=500, verbose_name='Sonstiges'),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='show',
            field=models.TextField(blank=True, help_text='Artists, Musikgenre, Performances; kurz  zusammengefasst', max_length=500, verbose_name='Programm'),
        ),
        migrations.AlterField(
            model_name='walkinggroupregistration',
            name='notes',
            field=models.TextField(blank=True, help_text='Sonstige Anmerkungen', max_length=500, verbose_name='Sonstiges'),
        ),
        migrations.AlterField(
            model_name='walkinggroupregistration',
            name='show',
            field=models.TextField(blank=True, help_text='Artists, Musikgenre, Performances; kurz  zusammengefasst', max_length=500, verbose_name='Programm'),
        ),
    ]
