# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantposted',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Gesamtbetrag der Anmeldung', verbose_name='Gesamtbetrag'),
            preserve_default=False,
        ),
    ]
