# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantPosted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csd_fr_registration.Applicant')),
            ],
        ),
    ]
