# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0002_applicantposted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcost',
            name='car_other_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer Auto Sonstige'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='car_queer_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer Auto queere Gruppen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='info_booth_other_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer Infostand Sonstige'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='info_booth_queer_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer Infostand queere Gruppen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='truck_other_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer LKW Sonstige'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='truck_queer_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer LKW queere Gruppen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='walking_group_music_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer Fußgruppen mit Musik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='walking_group_no_music_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Steuer Fußgruppen ohne Musik'),
            preserve_default=False,
        ),
    ]
