# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0002_auto_20160224_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_association',
            field=models.BooleanField(default=False, help_text='Handelt es sich um einen explizit queeren* Verein / Projekt / Gruppe (keine Unternehmen!)', verbose_name='queerer* Verein'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='is_car',
            field=models.BooleanField(default=False, help_text='Handelt es sich um einen PKW?', verbose_name='Auto?'),
            preserve_default=False,
        ),
    ]
