# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0003_auto_20160224_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Jahr (4-stellig)', unique=True, verbose_name='Jahr')),
                ('car_queer', models.PositiveIntegerField(verbose_name='Preis Auto queere Gruppen')),
                ('car_other', models.PositiveIntegerField(verbose_name='Preis Auto Sonstige')),
                ('truck_queer', models.PositiveIntegerField(verbose_name='Preis LKW queere Gruppen')),
                ('truck_other', models.PositiveIntegerField(verbose_name='Preis LKW Sonstige')),
                ('walking_group_no_music', models.PositiveIntegerField(verbose_name='Preis Fußgruppen ohne Musik')),
                ('walking_group_music', models.PositiveIntegerField(verbose_name='Preis Fußgruppen ohne Musik')),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street',
            field=models.CharField(help_text='Straße und Hausnummer', max_length=100, verbose_name='Straße'),
        ),
    ]
