# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0004_applicantposted_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcost',
            name='car_other_txt',
            field=models.CharField(default='PKW queere* Unternehmen, sonstige Gruppen', help_text='Artikelbeschreibung für Anzeige Auto Sonstige', max_length=100, verbose_name='Beschreibungstext Auto Sonstige'),
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='car_queer_txt',
            field=models.CharField(default='PKW queere* Gruppen', help_text='Artikelbeschreibung für Anzeige Auto queere Gruppen', max_length=100, verbose_name='Beschreibungstext Auto queere Gruppen'),
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='info_booth_other_txt',
            field=models.CharField(default='Infostand queere* Unternehmen, sonstige Gruppen', help_text='Artikelbeschreibung für Infostand Sonstige', max_length=100, verbose_name='Beschreibungstext Infostand Sonstige'),
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='info_booth_queer_txt',
            field=models.CharField(default='Infostand queere* Gruppen', help_text='Artikelbeschreibung für Infostand queere Gruppen', max_length=100, verbose_name='Beschreibungstext Infostand queere Gruppen'),
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='truck_other_txt',
            field=models.CharField(default='LKW queere* Unternehmen, sonstige Gruppen', help_text='Artikelbeschreibung für Anzeige LKW Sonstige', max_length=100, verbose_name='Beschreibungstext LKW Sonstige'),
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='truck_queer_txt',
            field=models.CharField(default='LKW queere* Gruppen', help_text='Artikelbeschreibung für Anzeige LKW queere Gruppen', max_length=100, verbose_name='Beschreibungstext LKW queere Gruppen'),
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='walking_group_music_txt',
            field=models.CharField(default='Fußgruppe mit Musik', help_text='Artikelbeschreibung für Anzeige Fußgruppen mit Musik', max_length=100, verbose_name='Beschreibungstext Fußgruppen mit Musik'),
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='walking_group_no_music_txt',
            field=models.CharField(default='Fußgruppe ohne Musik', help_text='Artikelbeschreibung für Anzeige Fußgruppen ohne Musik', max_length=100, verbose_name='Beschreibungstext Fußgruppen ohne Musik'),
        ),
    ]
