# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0004_auto_20160224_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcost',
            name='id',
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='info_booth_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Preis Infostand Sonstige'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationcost',
            name='info_booth_queer',
            field=models.PositiveIntegerField(default=0, verbose_name='Preis Infostand queere Gruppen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationcost',
            name='walking_group_music',
            field=models.PositiveIntegerField(verbose_name='Preis Fußgruppen mit Musik'),
        ),
        migrations.AlterField(
            model_name='registrationcost',
            name='year',
            field=models.PositiveIntegerField(help_text='Jahr (4-stellig)', primary_key=True, serialize=False, verbose_name='Jahr'),
        ),
    ]
