# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0005_auto_20160224_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantposted',
            name='amount',
        ),
        migrations.AddField(
            model_name='applicantposted',
            name='gross',
            field=models.PositiveIntegerField(default=0, help_text='Gesamtbetrag (brutto) der Anmeldung', verbose_name='Gesamtbetrag (brutto)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantposted',
            name='net',
            field=models.PositiveIntegerField(default=0, help_text='Gesamtbetrag (netto) der Anmeldung', verbose_name='Gesamtbetrag (netto)'),
            preserve_default=False,
        ),
    ]
