# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_fr_registration', '0005_auto_20160224_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='year',
            field=models.PositiveIntegerField(default=2016, help_text='Jahr (4-stellig)', verbose_name='Jahr'),
            preserve_default=False,
        ),
    ]
